---
title: "Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)

data(rest_inspec)

rest_inspec %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  spread(key = grade, value = n)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Relationship between tmax and tmin
```{r scatterplots}
rest_inspec %>%
  filter(!is.na(score), !is.na(grade), boro == "Manhattan") %>% 
  plot_ly(x = ~building, y = ~score, 
          type = "scatter", mode = "markers", 
          alpha = 0.5, color = ~boro)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Distribution of scores in different boroughs
```{r boxplot}
rest_inspec %>%
  filter(!is.na(score), boro != "Missing") %>% 
  plot_ly(y = ~score, color = ~boro, 
          type = "box", colors = "Set2")
```

### Number of A grade pizza restaurants in different boroughs

```{r barplot}
rest_inspec %>% 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) %>% 
  group_by(boro, grade) %>% 
  summarize(n = n()) %>% 
  spread(key = grade, value = n) %>%
  plot_ly(x = ~boro, y = ~A, color = ~boro, type = "bar")
```
